apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-cluster-role 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces", "services", "persistentvolumeclaims", "secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["create", "get", "list", "watch", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-cluster-binding
subjects:
- kind: ServiceAccount
  name: argo-workflow-manager
  namespace: default
roleRef:
  kind: ClusterRole
  name: argo-workflow-cluster-role
  apiGroup: rbac.authorization.k8s.io